import React from 'react';
import ReactMarkdown from 'react-markdown'; // We need to install this potentially, or just render raw text for now if not available.
// Actually, standard react doesn't render MD. I'll stick to simple text mapping or use a library if I can install it.
// I'll assume I can install 'react-markdown' or just render it as whitespace-pre-wrap for now to avoid package issues if install fails.

const ReportView = ({ report }) => {
    return (
        <div className="w-full max-w-4xl bg-white shadow-2xl rounded-lg overflow-hidden border border-gray-200 my-8">
            <div className="bg-gray-900 p-6 text-white border-b border-gray-800">
                <h2 className="text-2xl font-bold">Implementation Plan</h2>
                <p className="opacity-70 text-sm mt-1">Generated by Daniel @ Rectangle Red</p>
            </div>

            <div className="p-8 prose max-w-none text-gray-800">
                {/* Simple whitespace handling for markdown if library missing */}
                <pre className="whitespace-pre-wrap font-sans text-sm md:text-base leading-relaxed">
                    {report}
                </pre>
            </div>

            <div className="p-6 bg-gray-50 border-t border-gray-200 flex justify-end space-x-4">
                <button
                    onClick={() => window.print()}
                    className="px-4 py-2 bg-gray-200 hover:bg-gray-300 rounded text-gray-800 font-medium transition-colors"
                >
                    Print
                </button>
                <button className="px-4 py-2 bg-red-600 hover:bg-red-700 rounded text-white font-medium shadow transition-colors">
                    Contact Us to Start
                </button>
            </div>
        </div>
    );
};

export default ReportView;
